Repository maujogue/transcendence, pull requests merged in 2024-06, with the labels that each got.

#94 Stats front
  Makefile
  disableMailVerification.py
  frontend/css/index.css
  frontend/html/Dashboard.html
  frontend/html/Sidebar.html
  frontend/index.html
  frontend/js/ApiCalls.js
  frontend/js/ApiUtils.js
  frontend/js/DashboardUtils.js
  frontend/js/Modules.js
  frontend/js/Router.js
  frontend/js/Utils.js
  frontend/js/modules/auth42/auth42.html
  frontend/js/modules/auth42/auth42.js
  frontend/js/modules/emailInputModule/emailInputModule.html
  frontend/js/modules/emailInputModule/emailInputModule.js
  frontend/js/modules/statisticsModule/CustomChart.js
  frontend/js/modules/statisticsModule/chartConfigs.js
  frontend/js/modules/statisticsModule/statisticsModule.html
  frontend/js/modules/statisticsModule/statisticsModule.js
  frontend/js/modules/usernameInputModule/usernameInputModule.html
  frontend/js/modules/usernameInputModule/usernameInputModule.js
  frontend/js/pages/dashboard.js
  frontend/js/pages/emailVerified.js
  frontend/js/pages/game.js
  frontend/js/pages/sidebar.js
  frontend/js/pong/createField.js
  frontend/js/pong/displayCharacter.js
  frontend/js/pong/handlerMessage.js
  frontend/js/pong/loadModels.js
  frontend/js/pong/online.js
  frontend/js/pong/resize.js
  py_backend/stats/urls.py
  py_backend/stats/views.py
  py_backend/users/urls.py
  py_backend/users/views/check_user_logged_in.py
Labels: enhancement, fix

#98 Translations
  frontend/css/index.css
  frontend/html/About.html
  frontend/html/Dashboard.html
  frontend/html/EmailVerified.html
  frontend/html/Sidebar.html
  frontend/index.html
  frontend/js/ApiCalls.js
  frontend/js/Modules.js
  frontend/js/Router.js
  frontend/js/Utils.js
  frontend/js/modules/auth42/auth42.html
  frontend/js/modules/emailInputModule/emailInputModule.html
  frontend/js/modules/statisticsModule/statisticsModule.html
  frontend/js/modules/statisticsModule/statisticsModule.js
  frontend/js/modules/translationsModule/documentation.md
  frontend/js/modules/translationsModule/translationsModule.html
  frontend/js/modules/translationsModule/translationsModule.js
  frontend/js/modules/usernameInputModule/usernameInputModule.html
  frontend/js/pages/EmailVerified.js
  frontend/js/pages/Sidebar.js
  frontend/js/pages/dashboard.js
  frontend/js/pages/game.js
  frontend/js/pages/sidebar.js
  frontend/js/pong/createEndScreen.js
  frontend/js/pong/createTournament.js
  frontend/js/pong/joinTournament.js
  frontend/js/pong/menu.js
  frontend/translations/en.json
  frontend/translations/es.json
  frontend/translations/fr.json
  py_backend/auth42/tests.py
  py_backend/auth42/views.py
  py_backend/py_backend/settings.py
  py_backend/users/models.py
  py_backend/users/test/test_get_user_datas.py
  py_backend/users/test/test_profile_update.py
  py_backend/users/urls.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/update_lang.py
Labels: documentation, enhancement, refactoring

#105 Double friend request issue
  py_backend/friends/consumers.py
Labels: fix

#108 Add tournament name view
  py_backend/users/test/test_profile_update.py
  py_backend/users/test/test_verification_email.py
  py_backend/users/urls.py
  py_backend/users/utils.py
  py_backend/users/views/__init__.py
  py_backend/users/views/update_tournament_name.py
Labels: enhancement

#110 AI
  frontend/assets/img/icon/Multiplayer.png
  frontend/assets/img/icon/Solo.png
  frontend/css/pong.css
  frontend/index.html
  frontend/js/pages/game.js
  frontend/js/pong/AI/AIUtils.js
  frontend/js/pong/AI/models/agent1____0.70avg_/group1-shard1of1.bin
  frontend/js/pong/AI/models/agent1____0.70avg_/model.json
  frontend/js/pong/AI/models/agent2____2.10avg_/group1-shard1of1.bin
  frontend/js/pong/AI/models/agent2____2.10avg_/model.json
  frontend/js/pong/collision.js
  frontend/js/pong/createBall.js
  frontend/js/pong/createPlayer.js
  frontend/js/pong/handleKeyPress.js
  frontend/js/pong/initGame.js
  frontend/js/pong/menu.js
  frontend/static/json_model/group1-shard1of1.bin
  frontend/static/json_model/model.json
  py_backend/users/migrations/0001_initial.py
Labels: enhancement
