Repository maujogue/transcendence, pull requests merged in 2024-04, with the labels that each got.

#33 Start tournaments
  py_backend/py_backend/settings.py
  py_backend/py_backend/urls.py
  py_backend/requirements.txt
  py_backend/tournaments/__init__.py
  py_backend/tournaments/admin.py
  py_backend/tournaments/apps.py
  py_backend/tournaments/migrations/0001_initial.py
  py_backend/tournaments/migrations/__init__.py
  py_backend/tournaments/models.py
  py_backend/tournaments/test/__init__.py
  py_backend/tournaments/test/tests_view.py
  py_backend/tournaments/urls.py
  py_backend/tournaments/views.py
  py_backend/users/admin.py
  py_backend/users/models.py
Labels: enhancement

#36 Improved interface
  frontend/assets/img/character_icon/chupacabra.png
  frontend/assets/img/character_icon/elvis.png
  frontend/assets/img/character_icon/granny.png
  frontend/assets/img/character_icon/peasant.png
  frontend/assets/img/sprite/P1Sheet.png
  frontend/assets/img/sprite/P1SheetSmall.png
  frontend/assets/img/sprite/P2Sheet.png
  frontend/assets/img/sprite/P2SheetSmall.png
  frontend/assets/img/sprite/StartSheet.png
  frontend/assets/img/sprite/StartSheetSmall.png
  frontend/css/pong.css
  frontend/js/pong/Class/Character.js
  frontend/js/pong/createEndScreen.js
  frontend/js/pong/createPlayer.js
  frontend/js/pong/displayCharacter.js
  frontend/js/pong/handlerMessage.js
  frontend/js/pong/initGame.js
  frontend/js/pong/loadModels.js
  frontend/js/pong/main.js
  frontend/js/pong/menu.js
  frontend/js/pong/online.js
  frontend/js/pong/resize.js
  frontend/js/pong/varGlobal.js
  py_backend/multiplayer/consumers.py
Labels: enhancement

#38 Delete tournament
  py_backend/tournaments/migrations/0002_tournament_participants.py
  py_backend/tournaments/migrations/0003_alter_tournament_name.py
  py_backend/tournaments/models.py
  py_backend/tournaments/test/tests_view.py
  py_backend/tournaments/urls.py
  py_backend/tournaments/views.py
Labels: enhancement

#40 Update picture and profile
  py_backend/docker/Dockerfile.dev
  py_backend/media/hunter.jpg
  py_backend/media/profile_avatars/hunter.jpg
  py_backend/media/profile_avatars/hunter_2SgsU8a.jpg
  py_backend/media/profile_avatars/hunter_4ipV0nO.jpg
  py_backend/media/profile_avatars/hunter_EtlBTpf.jpg
  py_backend/media/profile_avatars/hunter_XaVmpK2.jpg
  py_backend/media/profile_avatars/hunter_aDlEVrn.jpg
  py_backend/media/profile_avatars/hunter_nulDRAr.jpg
  py_backend/media/profile_avatars/hunter_paJeyv1.jpg
  py_backend/media/profile_avatars/hunter_sPJX2mb.jpg
  py_backend/py_backend/settings.py
  py_backend/requirements.txt
  py_backend/users/admin.py
  py_backend/users/forms.py
  py_backend/users/migrations/0001_initial.py
  py_backend/users/migrations/0003_alter_customuser_email_alter_customuser_username.py
  py_backend/users/migrations/0004_delete_leaderboard_delete_tournament.py
  py_backend/users/migrations/0005_profile.py
  py_backend/users/migrations/0006_alter_customuser_bio.py
  py_backend/users/migrations/0007_alter_customuser_avatar.py
  py_backend/users/migrations/0008_alter_customuser_avatar.py
  py_backend/users/migrations/__init__.py
  py_backend/users/models.py
  py_backend/users/test/test_views.py
  py_backend/users/test_html/register_test.html
  py_backend/users/utils.py
  py_backend/users/views.py
Labels: enhancement

#42 Interface tournament
  docker/docker-compose.yaml
  frontend/assets/img/icon/1v1.png
  frontend/assets/img/icon/Tournament.png
  frontend/css/pong.css
  frontend/js/pong/createEndScreen.js
  frontend/js/pong/createTournament.js
  frontend/js/pong/main.js
  frontend/js/pong/menu.js
  frontend/js/pong/online.js
  py_backend/py_backend/settings.py
Labels: enhancement

#44 Websockets + nginx conf + router
  .github/workflows/django.yml
  Makefile
  docker/.env.prod
  docker/docker-compose.prod.yaml
  docker/docker-compose.yaml
  frontend/Dockerfile
  frontend/config/nginx.conf
  frontend/config/old.conf
  frontend/html/LandingPage.html
  frontend/index.html
  frontend/js/apiCall.js
  frontend/js/index.js
  frontend/js/pong/online.js
  nginx_proxy/config/Dockerfile
  nginx_proxy/config/nginx.conf
  py_backend/docker/Dockerfile.dev
  py_backend/docker/Dockerfile.prod
  py_backend/docker/entrypoint.dev.sh
  py_backend/docker/entrypoint.prod.sh
  py_backend/docker/requirements.txt
  py_backend/py_backend/settings.py
  py_backend/requirements.txt
  py_backend/users/validators.py
Labels: bug, enhancement

#51 49 login always returns error | login returns user's infos | update_profile views
  frontend/css/sidebar.css
  py_backend/users/forms.py
  py_backend/users/migrations/0001_initial.py
  py_backend/users/migrations/0005_profile.py
  py_backend/users/migrations/0006_alter_customuser_bio.py
  py_backend/users/migrations/0007_alter_customuser_avatar.py
  py_backend/users/migrations/0008_alter_customuser_avatar.py
  py_backend/users/migrations/__init__.py
  py_backend/users/models.py
  py_backend/users/test/test_views.py
  py_backend/users/urls.py
  py_backend/users/views.py
Labels: enhancement, fix

#58 Update profile picture
  py_backend/multiplayer/consumers.py
  py_backend/users/test/test_views.py
  py_backend/users/urls.py
  py_backend/users/utils.py
  py_backend/users/views/__init__.py
  py_backend/users/views/email_available.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/login.py
  py_backend/users/views/logout_view.py
  py_backend/users/views/register.py
  py_backend/users/views/update_profile_bio.py
  py_backend/users/views/update_profile_password.py
  py_backend/users/views/update_profile_picture.py
  py_backend/users/views/update_profile_username.py
  py_backend/users/views/username_availaible.py
Labels: enhancement

#63 Update profile/password
  frontend/html/Dashboard.html
  frontend/html/Sidebar.html
  frontend/js/ApiCalls.js
  frontend/js/Dashboard.js
  frontend/js/Router.js
  frontend/js/Sidebar.js
  frontend/js/User.js
  frontend/js/Utils.js
  py_backend/users/views/update_profile_password.py
Labels: enhancement, refactoring, fix

#61 Update documentation
  py_backend/media/profile_avatars/hunter.jpg
  py_backend/users/doc/django-users-documentation.md
  py_backend/users/test/test_views.py
  py_backend/users/views/login.py
  py_backend/users/views/update_profile_bio.py
  py_backend/users/views/update_profile_picture.py
  py_backend/users/views/update_profile_username.py
Labels: documentation

#66 Get avatar
  py_backend/media/profile_avatars/hunter.jpg
  py_backend/users/test/test_views.py
  py_backend/users/utils.py
  py_backend/users/views/get_user_datas.py
Labels: enhancement

#71 Avatar update, profile infos separated and cleaner code
  .gitignore
  docker/docker-compose.prod.yaml
  frontend/html/Dashboard.html
  frontend/html/Sidebar.html
  frontend/js/ApiCalls.js
  frontend/js/ApiUtils.js
  frontend/js/Dashboard.js
  frontend/js/DashboardUtils.js
  frontend/js/User.js
  frontend/js/Utils.js
Labels: enhancement, refactoring, fix
