Repository maujogue/transcendence, pull requests merged in 2024-05, with the labels that each got.

#75 Stats api
  py_backend/history/admin.py
  py_backend/history/tests.py
  py_backend/history/views.py
  py_backend/multiplayer/consumers.py
  py_backend/py_backend/settings.py
  py_backend/py_backend/urls.py
  py_backend/stats/__init__.py
  py_backend/stats/apps.py
  py_backend/stats/doc/stats.md
  py_backend/stats/migrations/0001_initial.py
  py_backend/stats/migrations/__init__.py
  py_backend/stats/models.py
  py_backend/stats/tests.py
  py_backend/stats/urls.py
  py_backend/stats/views.py
  py_backend/tournaments/admin.py
Labels: enhancement

#83 Improved visual
  frontend/css/pong.css
  frontend/js/pages/Game.js
  frontend/js/pong/createEnvironment.js
  frontend/js/pong/menu.js
  frontend/js/pong/online.js
  frontend/js/pong/resize.js
  frontend/js/pong/spaceBackground.js
  frontend/js/pong/tournament.js
Labels: enhancement, fix

#87 Add db gitignore
  .gitignore
  Makefile
  py_backend/docker/entrypoint.prod.sh
  py_backend/users/migrations/0001_initial.py
  py_backend/users/migrations/0002_alter_customuser_email_is_verified.py
  py_backend/users/migrations/0003_alter_customuser_email_is_verified.py
  py_backend/users/migrations/__init__.py
Labels: fix

#88 Fix online
  docker/.env.prod
  frontend/css/pong.css
  frontend/js/pages/Game.js
  frontend/js/pong/handlerMessage.js
  frontend/js/pong/joinTournament.js
  frontend/js/pong/online.js
  frontend/js/pong/score.js
  frontend/js/pong/tournament.js
  py_backend/auth42/migrations/__init__.py
  py_backend/multiplayer/ball.py
  py_backend/multiplayer/consumers.py
  py_backend/multiplayer/player.py
  py_backend/tournaments/views.py
  py_backend/users/migrations/0001_initial.py
Labels: bug, fix

#91 42 auth
  .gitignore
  docker/.env.prod
  frontend/assets/img/42logo.png
  frontend/html/Dashboard.html
  frontend/html/Sidebar.html
  frontend/js/ApiCalls.js
  frontend/js/ApiUtils.js
  frontend/js/Modules.js
  frontend/js/Router.js
  frontend/js/User.js
  frontend/js/Utils.js
  frontend/js/modules/auth42.html
  frontend/js/modules/auth42.js
  frontend/js/modules/emailInputModule.html
  frontend/js/pages/Dashboard.js
  frontend/js/pages/Game.js
  frontend/js/pages/Sidebar.js
  py_backend/auth42/__init__.py
  py_backend/auth42/admin.py
  py_backend/auth42/apps.py
  py_backend/auth42/models.py
  py_backend/auth42/tests.py
  py_backend/auth42/urls.py
  py_backend/auth42/views.py
  py_backend/py_backend/settings.py
  py_backend/py_backend/urls.py
  py_backend/users/migrations/0001_initial.py
  py_backend/users/models.py
  py_backend/users/test/test_profile_update.py
  py_backend/users/urls.py
  py_backend/users/views/__init__.py
  py_backend/users/views/check_user_logged_in.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/login_view.py
  py_backend/users/views/update_email.py
  py_backend/users/views/update_profile_password.py
  py_backend/users/views/update_profile_username.py
  py_backend/users/views/username_available.py
Labels: enhancement

#92 Email validation front
  frontend/html/Dashboard.html
  frontend/html/EmailVerified.html
  frontend/js/Router.js
  frontend/js/Utils.js
  frontend/js/pages/EmailVerified.js
  py_backend/users/views/confirm_email.py
  py_backend/users/views/confirm_new_email.py
  py_backend/users/views/register.py
  py_backend/users/views/update_email.py
Labels: fix
