Repository maujogue/transcendence, pull requests merged in 2024-07, with the labels that each got.

#111 Revert "Merge pull request #110 from maujogue/AI"
  frontend/assets/img/icon/Multiplayer.png
  frontend/assets/img/icon/Solo.png
  frontend/css/pong.css
  frontend/index.html
  frontend/js/pages/game.js
  frontend/js/pong/AI/AIUtils.js
  frontend/js/pong/AI/models/agent1____0.70avg_/group1-shard1of1.bin
  frontend/js/pong/AI/models/agent1____0.70avg_/model.json
  frontend/js/pong/AI/models/agent2____2.10avg_/group1-shard1of1.bin
  frontend/js/pong/AI/models/agent2____2.10avg_/model.json
  frontend/js/pong/collision.js
  frontend/js/pong/createBall.js
  frontend/js/pong/createPlayer.js
  frontend/js/pong/handleKeyPress.js
  frontend/js/pong/initGame.js
  frontend/js/pong/menu.js
  frontend/static/json_model/group1-shard1of1.bin
  frontend/static/json_model/model.json
  py_backend/users/migrations/0001_initial.py
Labels: fix

#114 Simultaneous connection
  docker/.env.dev
  frontend/assets/img/es.png
  frontend/assets/img/fr.png
  frontend/assets/img/gb.png
  frontend/js/modules/friendList/friendsWs.js
  frontend/js/modules/translationsModule/translationsModule.html
  frontend/js/modules/translationsModule/translationsModule.js
  py_backend/friends/consumers.py
  py_backend/friends/migrations/0001_initial.py
  py_backend/friends/migrations/__init__.py
  py_backend/tournaments/consumers.py
  py_backend/tournaments/test/tests_view.py
  py_backend/users/decorators.py
  py_backend/users/test/test_get_user_datas.py
  py_backend/users/test/test_login.py
  py_backend/users/test/test_logout.py
  py_backend/users/test/test_profile_update.py
  py_backend/users/views/login_view.py
  py_backend/users/views/logout_view.py
Labels: enhancement

#118 Backend debug
  frontend/js/modules/friendList/friendsWs.js
  py_backend/friends/consumers.py
  py_backend/py_backend/settings.py
  py_backend/users/migrations/0001_initial.py
  py_backend/users/models.py
  py_backend/users/test/test_login.py
  py_backend/users/test/test_register.py
  py_backend/users/test/test_utils.py
  py_backend/users/test/test_verification_email.py
  py_backend/users/utils.py
  py_backend/users/validators.py
  py_backend/users/views/check_user_logged_in.py
  py_backend/users/views/email_available.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/login_view.py
  py_backend/users/views/update_email.py
  py_backend/users/views/update_lang.py
  py_backend/users/views/update_profile_bio.py
  py_backend/users/views/update_profile_password.py
  py_backend/users/views/update_profile_picture.py
  py_backend/users/views/update_profile_username.py
  py_backend/users/views/update_tournament_name.py
  py_backend/users/views/username_available.py
Labels: fix

#121 116 stat user id instead tournament username
  frontend/js/modules/gameModule/tournament.js
  frontend/js/modules/statisticsModule/statisticsModule.js
  py_backend/multiplayer/consumers.py
  py_backend/stats/models.py
  py_backend/stats/tests.py
  py_backend/stats/views.py
  py_backend/tournaments/bracket.py
  py_backend/tournaments/consumers.py
Labels: fix

#124 Deco after change username
  py_backend/friends/consumers.py
Labels: bug

#123 Blockchain Module
  docker/.env.dev
  docker/.env.prod
  frontend/css/pong.css
  frontend/js/modules/gameModule/tournament.js
  py_backend/docker/requirements.txt
  py_backend/package-lock.json
  py_backend/package.json
  py_backend/py_backend/settings.py
  py_backend/tournaments/__init__.py
  py_backend/tournaments/apps.py
  py_backend/tournaments/blockchain.py
  py_backend/tournaments/compiledSolidity.json
  py_backend/tournaments/consumers.py
  py_backend/tournaments/models.py
  py_backend/tournaments/signals.py
  py_backend/tournaments/urls.py
  py_backend/tournaments/views.py
  py_backend/users/views/update_profile_picture.py
Labels: enhancement

#126 Better button blockchain
  frontend/css/pong.css
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/tournament.js
  py_backend/docker/requirements.txt
Labels: fix

#127 Debug game
  frontend/js/modules/gameModule/online.js
  py_backend/multiplayer/consumers.py
  py_backend/multiplayer/models.py
  py_backend/tournaments/consumers.py
Labels: bug

#130 Fixed a bug in the online game.
  frontend/js/modules/gameModule/handleKeyPress.js
  frontend/js/modules/gameModule/online.js
Labels: fix

#134 Fix logout 401 error
  frontend/js/ApiCalls.js
  py_backend/py_backend/settings.py
  py_backend/users/decorators.py
  py_backend/users/test/test_login.py
  py_backend/users/test/test_logout.py
  py_backend/users/utils.py
  py_backend/users/views/logout_view.py
Labels: fix

#136 Deployment check
  Makefile
  docker/.env.dev
  docker/.env.prod
  frontend/assets/img/logo2.JPG
  frontend/assets/img/logo3.JPG
  frontend/assets/img/logo4.jpg
  frontend/config/nginx.conf
  frontend/css/index.css
  frontend/js/modules/gameModule/loadModels.js
  frontend/js/modules/gameModule/tournament.js
  frontend/js/modules/gameModule/varGlobal.js
  frontend/js/modules/translationsModule/translationsModule.html
  py_backend/auth42/views.py
  py_backend/docker/Dockerfile.dev
  py_backend/docker/Dockerfile.prod
  py_backend/package-lock.json
  py_backend/package.json
  py_backend/py_backend/settings.py
  py_backend/py_backend/urls.py
Labels: enhancement, fix

#137 Change SQLite to PostgreSQL
  .github/workflows/django.yml
  frontend/js/modules/tournamentUsernameInputModule/tournamentUsernameInputModule.html
  frontend/js/modules/usernameInputModule/usernameInputModule.html
  py_backend/py_backend/settings.py
  py_backend/users/utils.py
  py_backend/users/views/update_tournament_name.py
Labels: refactoring

#135 Tournament responsive + tournament timer
  frontend/css/dashboard.css
  frontend/css/pong.css
  frontend/html/Dashboard.html
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/gameModule.html
  frontend/js/modules/gameModule/handleKeyPress.js
  frontend/js/modules/gameModule/handlerMessage.js
  frontend/js/modules/gameModule/menu.js
  frontend/js/modules/gameModule/tournament.js
  frontend/js/modules/gameModule/varGlobal.js
  py_backend/multiplayer/consumers.py
  py_backend/tournaments/consumers.py
  translations/en.json
Labels: bug

#139 Backend protection update views
  frontend/js/Utils.js
  frontend/js/modules/gameModule/online.js
  py_backend/multiplayer/consumers.py
  py_backend/users/decorators.py
  py_backend/users/models.py
  py_backend/users/views/update_email.py
  py_backend/users/views/update_is_online.py
  py_backend/users/views/update_lang.py
  py_backend/users/views/update_profile_banner.py
  py_backend/users/views/update_profile_bio.py
  py_backend/users/views/update_profile_password.py
  py_backend/users/views/update_profile_picture.py
  py_backend/users/views/update_profile_username.py
  py_backend/users/views/update_tournament_name.py
  translations/en.json
Labels: enhancement

#140 Auth42 simultaneous connection
  docker/docker-compose.yaml
  frontend/html/Dashboard.html
  frontend/js/DashboardUtils.js
  frontend/js/User.js
  frontend/js/Utils.js
  frontend/js/modules/emailInputModule/emailInputModule.html
  frontend/js/modules/gameModule/handleKeyPress.js
  frontend/js/modules/usernameInputModule/usernameInputModule.html
  py_backend/auth42/tests.py
  py_backend/auth42/views.py
  py_backend/users/urls.py
  py_backend/users/views/update_is_online.py
  py_backend/users/views/update_profile_banner.py
  py_backend/users/views/update_profile_picture.py
  translations/en.json
  translations/es.json
  translations/fr.json
Labels: enhancement, fix

#141 Fix tournament
  frontend/js/modules/friendList/friendsWs.js
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/createEndScreen.js
  frontend/js/modules/gameModule/handleKeyPress.js
  frontend/js/modules/gameModule/handlerMessage.js
  frontend/js/modules/gameModule/menu.js
  frontend/js/modules/gameModule/online.js
  frontend/js/modules/gameModule/resize.js
  frontend/js/modules/gameModule/tournament.js
  py_backend/friends/consumers.py
  py_backend/py_backend/settings.py
  py_backend/tournaments/consumers.py
  py_backend/users/models.py
  py_backend/users/test/test_get_user_datas.py
  py_backend/users/test/test_utils.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/login_view.py
Labels: bug

#133 Ai
  frontend/assets/img/icon/Multiplayer.png
  frontend/assets/img/icon/Solo.png
  frontend/css/pong.css
  frontend/index.html
  frontend/js/modules/AIModule/AI.js
  frontend/js/modules/AIModule/envForAI.js
  frontend/js/modules/AIModule/model/model.json
  frontend/js/modules/AIModule/model/model.weights.bin
  frontend/js/modules/gameModule/Class/Player.js
  frontend/js/modules/gameModule/collision.js
  frontend/js/modules/gameModule/gameModule.js
  frontend/js/modules/gameModule/handleKeyPress.js
  frontend/js/modules/gameModule/menu.js
  py_backend/users/migrations/0001_initial.py
  translations/en.json
  translations/es.json
  translations/fr.json
Labels: enhancement

#143 Small fixes
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/tournament.js
  py_backend/users/migrations/0001_initial.py
Labels: fix

#142 Fixing game bugs
  frontend/js/modules/AIModule/AI.js
  frontend/js/modules/gameModule/collision.js
  frontend/js/modules/gameModule/gameModule.js
  frontend/js/modules/gameModule/loadModels.js
Labels: fix

#148 Add a waiting test when pressing 'play again' in quickplay
  frontend/css/pong.css
  frontend/js/modules/gameModule/online.js
  translations/en.json
  translations/es.json
  translations/fr.json
Labels: enhancement

#147 Final fix
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/createTournament.js
  frontend/js/modules/gameModule/online.js
  frontend/js/modules/gameModule/tournament.js
  py_backend/multiplayer/consumers.py
  py_backend/py_backend/settings.py
  py_backend/tournaments/bracket.py
  py_backend/tournaments/consumers.py
  py_backend/tournaments/models.py
Labels: fix

#151 protect for double error msg and improved bracket
  frontend/css/pong.css
  frontend/js/modules/gameModule/createBracket.js
  frontend/js/modules/gameModule/tournament.js
  frontend/js/modules/gameModule/varGlobal.js
Labels: fix

#152 Fix blockchain
  docker/.env.prod
  frontend/js/modules/gameModule/tournament.js
  py_backend/tournaments/blockchain.py
  py_backend/tournaments/consumers.py
  py_backend/tournaments/models.py
  py_backend/tournaments/signals.py
  py_backend/tournaments/views.py
  translations/es.json
Labels: fix

#154 Add try except tournaments
  py_backend/tournaments/views.py
  translations/en.json
  translations/es.json
  translations/fr.json
Labels: enhancement

#155 fix double email issue
  py_backend/users/models.py
  py_backend/users/utils.py
  py_backend/users/views/confirm_new_email.py
  py_backend/users/views/update_email.py
Labels: fix

#158 Train ai
  frontend/js/modules/AIModule/AI.js
  frontend/js/modules/AIModule/model/model.weights.bin
  frontend/js/modules/gameModule/gameModule.js
Labels: enhancement

#156 Fix ingame status
  frontend/js/modules/gameModule/createBracket.js
  py_backend/multiplayer/consumers.py
  py_backend/py_backend/settings.py
  py_backend/tournaments/consumers.py
Labels: fix

#160 add forbidden usernames and fct
  .github/workflows/django.yml
  frontend/translations/en.json
  frontend/translations/es.json
  frontend/translations/fr.json
  py_backend/users/forbidden_usernames.py
  py_backend/users/test/test_profile_update.py
  py_backend/users/test/test_utils.py
  py_backend/users/utils.py
Labels: enhancement

#159 fix reverse bracket
  .gitignore
  Makefile
  docker/docker-compose.prod.yaml
  docker/docker-compose.yaml
  frontend/css/dashboard.css
  frontend/html/Dashboard.html
  py_backend/docker/Dockerfile
  py_backend/docker/Dockerfile.dev
  py_backend/docker/entrypoint.prod.sh
  py_backend/docker/entrypoint.sh
  py_backend/tournaments/bracket.py
Labels: fix

#162 devops fixes
  Makefile
  docker-compose.yaml
  py_backend/py_backend/settings.py
Labels: fix

#163 fix back views
  frontend/js/modules/statisticsModule/statisticsModule.js
  py_backend/auth42/views.py
  py_backend/py_backend/settings.py
  py_backend/stats/urls.py
  py_backend/tournaments/views.py
  py_backend/users/utils.py
  py_backend/users/views/get_user_datas.py
  py_backend/users/views/update_is_online.py
  py_backend/users/views/update_profile_password.py
Labels: fix
