Repository maujogue/transcendence, pull requests merged in 2024-03, with the labels that each got.

#22 11 restart after backmenu
  Makefile
  docker/.env.dev
  docker/docker-compose.yaml
  frontend/Dockerfile
  frontend/config/nginx.conf
  frontend/js/pong/createPlayer.js
  frontend/js/pong/displayCharacter.js
  frontend/js/pong/getColorChoose.js
  frontend/js/pong/handlerMessage.js
  frontend/js/pong/online.js
  frontend/js/pong/sendMessage.js
  nginx_proxy/config/nginx.conf
  py_backend/docker/Dockerfile.dev
  py_backend/docker/cert.pem
  py_backend/docker/entrypoint.dev.sh
  py_backend/docker/key.pem
  py_backend/multiplayer/consumers.py
  py_backend/multiplayer/player.py
  py_backend/multiplayer/routing.py
  py_backend/py_backend/asgi.py
  py_backend/py_backend/settings.py
  py_backend/requirements.txt
Labels: bug

#25 Friendlist
  py_backend/friends/__init__.py
  py_backend/friends/admin.py
  py_backend/friends/apps.py
  py_backend/friends/migrations/0001_initial.py
  py_backend/friends/migrations/0002_alter_friendrequest_from_user_and_more.py
  py_backend/friends/migrations/0003_alter_friendrequest_status.py
  py_backend/friends/migrations/__init__.py
  py_backend/friends/models.py
  py_backend/friends/test/__init__.py
  py_backend/friends/test/test_views.py
  py_backend/friends/urls.py
  py_backend/friends/views.py
  py_backend/py_backend/settings.py
  py_backend/py_backend/urls.py
  py_backend/users/migrations/0003_customuser_friends.py
  py_backend/users/models.py
  py_backend/users/test/test_views.py
  py_backend/users/tests.py
  py_backend/users/urls.py
  py_backend/users/views.py
Labels: enhancement

#24 paddle clip and fix collisions paddle with area border
  frontend/js/pong/handlerMessage.js
  frontend/js/pong/online.js
  py_backend/multiplayer/ball.py
  py_backend/multiplayer/consumers.py
  py_backend/multiplayer/player.py
Labels: bug

#29 Added lights in game
  frontend/js/pong/createField.js
  frontend/js/pong/handleKeyPress.js
  frontend/js/pong/initGame.js
  frontend/js/pong/menu.js
  frontend/js/pong/varGlobal.js
Labels: bug

#31 Validation register
  py_backend/friends/doc/django-friends-documentation.md
  py_backend/friends/migrations/0004_rename_friendrequest_interactionrequest.py
  py_backend/friends/models.py
  py_backend/friends/views.py
  py_backend/media/avatar.jpg
  py_backend/py_backend/settings.py
  py_backend/users/admin.py
  py_backend/users/doc/django-users-documentation.md
  py_backend/users/forms.py
  py_backend/users/migrations/0001_initial.py
  py_backend/users/migrations/0002_alter_customuser_avatar.py
  py_backend/users/migrations/0003_alter_customuser_email_alter_customuser_username.py
  py_backend/users/migrations/0003_customuser_friends.py
  py_backend/users/migrations/0004_delete_leaderboard_delete_tournament.py
  py_backend/users/models.py
  py_backend/users/test/test_views.py
  py_backend/users/test_html/login_test.html
  py_backend/users/urls.py
  py_backend/users/utils.py
  py_backend/users/views.py
Labels: documentation, enhancement
